export const projects = [
  {
    title: 'TabibRDV',
    description: "TabibRDV - plateforme de prise de rendez-vous en ligne chez les professionnel(le)s de santé. Projet fait en collaboration avec M.Naim",
      image: '/images/tabibrdv.png',
      presta: 'B.Youcef - M.Naim',
      client: 'B.Youcef - M.Naim',
      role: 'FullStack - DevOps',
      tags: ['Angular', 'Express', 'SpringBoot', 'MySQL'],
      link: 'https://tabibrdv.com',
    id: 0,
  },
  {
    title: 'Mon Projet',
    description:"Projet à vendre - plateforme de gestion de projets adaptée à differents secteurs : BTP, IT etc... test authentication => identifiant: youcef - mdp: youcef",
    image: '/images/maruche.png',
    presta: 'B.Youcef',
    client: 'B.Youcef',
    role: 'FullStack - DevOps',
    tags: ['React', 'JavaScript', 'Node Js', 'MongoDB'],
    link: 'https://ma-ruche-youcef-belaidi.netlify.app',
    id: 1,
  },
  {
    title: 'Ma Météo',
    description:"Application pour la Météo",
    image: '/images/meteo.png',
    presta: 'B.Youcef',
    client: 'B.Youcef',
    role: 'FullStack - DevOps',
    tags: ['React', 'JavaScript'],
    link: 'https://youcefbelaidi.netlify.app/',
    id: 2,
  },
  {
    title: 'Smart Tracer',
    description: "Smart Tracer est une application PWA qui a pour but de faciliter le nettoyage et la désinfection des trains et stations de la RATP. Elle a pour but également de suivre en temps réel les contrôles effectués pour pouvoir détecter les anomalies des trains et garder une traçabilité des actions et réparations faites ou à faire.",
      image: '/images/ratp.jpg',
      presta: 'Capgemini',
      client: 'RATP',
      role: 'FullStack',
      tags: ['React', 'Node Js', 'PostgreSQL', 'Express'],
      link: '',
    id: 3,
  },
  {
    title: 'Sesame',
    description: "Intervention sur un projet pour l’association Voisin Malin en leur fournissant une application pour gérer ses missions, enquêtes et sessions de porte à porte.",
    image: '/images/VoisinMalin.jpg',
    presta: 'Capgemini',
    client: 'Voisin Malin',
    role: 'FullStack - DevOps',
    tags: ['Angular', 'Node Js', 'AWS Serverless - Amplify'],
    link: '',
    id: 4,
  },
  {
    title: 'Camera Control',
    description: "L'ojectif est de contrôler la qualité de production de voitures grâce à des données captées par des caméras et un traitement via une intelligence artificielle",
    image: '/images/PSA.jpg',
    presta: 'Capgemini',
    client: 'Group PSA - Peugeot',
    role: 'DevOps',
    tags: ['AWS', 'Terraform'],
    link: '',
    id: 5,
  },
];

export const TimeLineData = [
  // { year: 2017, text: 'Started my journey', },
  // { year: 2018, text: 'Worked as a freelance developer', },
  // { year: 2019, text: 'Founded JavaScript Mastery', },
  // { year: 2020, text: 'Shared my projects with the world', },
  // { year: 2021, text: 'Started my own platform', },
];